swagger: '2.0'
info:
  version: "1.0.0"
  title: UserServer Swagger
  contact:
    name: Contact the developer
    url: https://t.me/viewsharp
tags:
  - name: user
    description: Operations about user
paths:
  '/user':
    post:
      operationId: postUser
      tags:
        - user
      summary: Create user
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/UserCreatingData'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid format (the scheme depends on the implementation of the code generator)
        '422':
          description: Invalid format (the scheme depends on the implementation of the code generator)
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
  '/user/{id}':
    get:
      operationId: getUser
      tags:
        - user
      summary: Get user by id
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/User'
        '404':
          description: User not found
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
    patch:
      operationId: patchUser
      tags:
        - user
      summary: Updated user
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          type: string
        - name: body
          in: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/UserEditingData'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid format (the scheme depends on the implementation of the code generator)
        '404':
          description: User not found
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
    delete:
      operationId: deleteUser
      tags:
        - user
      summary: Delete user
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          type: string
      responses:
        '200':
          description: Success
        '404':
          description: User not found
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
definitions:
  UserCreatingData:
    type: object
    properties:
      name:
        type: string
        maxLength: 64
      birth_date:
        type: string
        format: date
    required:
      - name
      - birth_date
  UserEditingData:
    type: object
    properties:
      name:
        type: string
        maxLength: 64
        x-nullable: true
      birth_date:
        type: string
        format: date
        x-nullable: true
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
        maxLength: 64
      birth_date:
        type: string
        format: date
    required:
      - id
      - name
      - birth_date
  Error:
    type: object
    properties:
      error:
        type: string
    required:
      - error